AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instances in VPC

Resources:
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cde6390e61a03eee # Replace with a valid AMI ID
      SubnetId: !ImportValue PublicSubnetId
      SecurityGroupIds:
        - !ImportValue PublicEC2SecurityGroup
      KeyName: my_key_pair  # Replace with your key pair name
      Tags:
        - Key: Name
          Value: PublicEC2Instance

  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0bdb3829e2e8f8686 # Replace with a valid AMI ID
      SubnetId: !ImportValue PrivateSubnetId
      SecurityGroupIds:
        - !ImportValue PrivateEC2SecurityGroup
      KeyName: my_key_pair  # Replace with your key pair name
      Tags:
        - Key: Name
          Value: PrivateEC2Instance