AWSTemplateFormatVersion: '2010-09-09'
Description: Internet Gateway

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyInternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue MyVPCId
      InternetGatewayId: !Ref InternetGateway

Outputs:
  InternetGatewayId:
    Description: The Internet Gateway ID
    Value: !Ref InternetGateway
    Export:
      Name: InternetGatewayId