AWSTemplateFormatVersion: '2010-09-09'
Description: NAT Gateway for VPC

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !ImportValue PublicSubnetId
      Tags:
        - Key: Name
          Value: NATGateway

Outputs:
  NATGatewayId:
    Description: The NAT Gateway ID
    Value: !Ref NATGateway
    Export:
      Name: NATGatewayId